/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agents
         * @description Get all agents with optional filters
         */
        get: operations["get_agents_api_agents__get"];
        put?: never;
        /**
         * Create Agent
         * @description Create a new agent
         */
        post: operations["create_agent_api_agents__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Get a single agent by ID
         */
        get: operations["get_agent_api_agents__agent_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Agent
         * @description Delete an agent
         */
        delete: operations["delete_agent_api_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Agent
         * @description Update an agent
         */
        patch: operations["update_agent_api_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assignments
         * @description Get all participant-agent assignments with optional filters
         */
        get: operations["get_assignments_api_assignments__get"];
        put?: never;
        /**
         * Create Assignment
         * @description Create a new participant-agent assignment
         */
        post: operations["create_assignment_api_assignments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assignment
         * @description Get a single assignment by ID
         */
        get: operations["get_assignment_api_assignments__assignment_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Assignment
         * @description Delete an assignment
         */
        delete: operations["delete_assignment_api_assignments__assignment_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Assignment
         * @description Update an assignment
         */
        patch: operations["update_assignment_api_assignments__assignment_id__patch"];
        trace?: never;
    };
    "/api/assignments/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bulk Assignments
         * @description Create multiple assignments at once
         */
        post: operations["create_bulk_assignments_api_assignments_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversations
         * @description Get conversation logs with optional filters
         */
        get: operations["get_conversations_api_conversations__get"];
        put?: never;
        /**
         * Create Conversation
         * @description Create a new conversation log
         */
        post: operations["create_conversation_api_conversations__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a single conversation log by ID
         */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a conversation log
         */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Participants
         * @description Get all participants with optional filters
         */
        get: operations["get_participants_api_participants__get"];
        put?: never;
        /**
         * Create Participant
         * @description Create a new participant
         */
        post: operations["create_participant_api_participants__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Participant
         * @description Get a single participant with their agent assignments
         */
        get: operations["get_participant_api_participants__participant_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Participant
         * @description Delete a participant
         */
        delete: operations["delete_participant_api_participants__participant_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Participant
         * @description Update a participant
         */
        patch: operations["update_participant_api_participants__participant_id__patch"];
        trace?: never;
    };
    "/api/participants/{participant_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Participant Conversations
         * @description Get all conversations for a specific participant
         */
        get: operations["get_participant_conversations_api_participants__participant_id__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/complete-assignment/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Assignment
         * @description Mark an assignment as completed for a participant.
         *     This moves the participant to the next assignment if available.
         */
        post: operations["complete_assignment_api_session_complete_assignment__participant_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/participant-config/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Participant Config
         * @description Get the agent configuration assigned to a participant.
         *     Returns the active agent assignment and experiment prompt details.
         */
        get: operations["get_participant_config_api_session_participant_config__participant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** Assignment */
        Assignment: {
            /** Agent Config */
            agent_config: string;
            /** Agent Name */
            agent_name: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Experiment Prompt Id */
            experiment_prompt_id: string;
            /** Id */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** Participant Id */
            participant_id: string;
        };
        /** AssignmentCreate */
        AssignmentCreate: {
            /** Agent Config */
            agent_config: string;
            /** Agent Name */
            agent_name: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Experiment Prompt Id */
            experiment_prompt_id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** Participant Id */
            participant_id: string;
        };
        /** AssignmentUpdate */
        AssignmentUpdate: {
            /** Completed */
            completed?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Notes */
            notes?: string | null;
            /** Order */
            order?: number | null;
        };
        /** CompleteAssignmentRequest */
        CompleteAssignmentRequest: {
            /** Assignment Id */
            assignment_id: string;
        };
        /** ConversationLog */
        ConversationLog: {
            /** Agent Config */
            agent_config: string;
            /** Agent Name */
            agent_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration */
            duration: number;
            /** Experiment Id */
            experiment_id?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /** Id */
            id: string;
            /** Participant Id */
            participant_id?: string | null;
            /** Session Id */
            session_id: string;
            /** Task Completed */
            task_completed?: boolean | null;
            /** Transcript */
            transcript: Record<string, never>;
            /** Turn Count */
            turn_count: number;
            /** User Satisfaction */
            user_satisfaction?: number | null;
        };
        /** ConversationLogCreate */
        ConversationLogCreate: {
            /** Agent Config */
            agent_config: string;
            /** Agent Name */
            agent_name: string;
            /** Duration */
            duration: number;
            /** Experiment Id */
            experiment_id?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /** Participant Id */
            participant_id?: string | null;
            /** Session Id */
            session_id: string;
            /** Task Completed */
            task_completed?: boolean | null;
            /** Transcript */
            transcript: Record<string, never>;
            /** Turn Count */
            turn_count: number;
            /** User Satisfaction */
            user_satisfaction?: number | null;
        };
        /** ExperimentPrompt */
        ExperimentPrompt: {
            /** Agent Config */
            agent_config: string;
            /** Agent Name */
            agent_name: string;
            /** Avg Duration */
            avg_duration?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Instructions */
            instructions?: string | null;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Name */
            name: string;
            /** Success Rate */
            success_rate?: number | null;
            /** System Prompt */
            system_prompt: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Temperature
             * @default 0.8
             */
            temperature: number | null;
            /** Total Runs */
            total_runs: number;
            /** Updated At */
            updated_at?: string | null;
            /** Voice */
            voice?: string | null;
        };
        /** ExperimentPromptCreate */
        ExperimentPromptCreate: {
            /** Agent Config */
            agent_config: string;
            /** Agent Name */
            agent_name: string;
            /** Description */
            description?: string | null;
            /** Instructions */
            instructions?: string | null;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Name */
            name: string;
            /** System Prompt */
            system_prompt: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Temperature
             * @default 0.8
             */
            temperature: number | null;
            /** Voice */
            voice?: string | null;
        };
        /** ExperimentPromptUpdate */
        ExperimentPromptUpdate: {
            /** Avg Duration */
            avg_duration?: number | null;
            /** Description */
            description?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Name */
            name?: string | null;
            /** Success Rate */
            success_rate?: number | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Temperature */
            temperature?: number | null;
            /** Voice */
            voice?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Participant */
        Participant: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /** Id */
            id: string;
            /**
             * Is Guest
             * @default false
             */
            is_guest: boolean;
            /** Name */
            name?: string | null;
            /** Participant Id */
            participant_id: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ParticipantCreate */
        ParticipantCreate: {
            /** Email */
            email?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /**
             * Is Guest
             * @default false
             */
            is_guest: boolean;
            /** Name */
            name?: string | null;
            /** Participant Id */
            participant_id: string;
        };
        /** ParticipantUpdate */
        ParticipantUpdate: {
            /** Email */
            email?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /** Name */
            name?: string | null;
        };
        /** ParticipantWithAssignments */
        ParticipantWithAssignments: {
            /**
             * Assignments
             * @default []
             */
            assignments: components["schemas"]["Assignment"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /** Id */
            id: string;
            /**
             * Is Guest
             * @default false
             */
            is_guest: boolean;
            /** Name */
            name?: string | null;
            /** Participant Id */
            participant_id: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_agents_api_agents__get: {
        parameters: {
            query?: {
                agent_config?: string | null;
                agent_name?: string | null;
                is_active?: boolean | null;
                tags?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPrompt"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_agents__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentPromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPrompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPrompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentPromptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPrompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignments_api_assignments__get: {
        parameters: {
            query?: {
                experiment_prompt_id?: string | null;
                is_active?: boolean | null;
                participant_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assignment_api_assignments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignment_api_assignments__assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assignment_api_assignments__assignment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_assignment_api_assignments__assignment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bulk_assignments_api_assignments_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversations_api_conversations__get: {
        parameters: {
            query?: {
                agent_config?: string | null;
                experiment_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_conversations__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participants_api_participants__get: {
        parameters: {
            query?: {
                is_guest?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_participant_api_participants__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_api_participants__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantWithAssignments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_participant_api_participants__participant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_participant_api_participants__participant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_conversations_api_participants__participant_id__conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_assignment_api_session_complete_assignment__participant_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_config_api_session_participant_config__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
